### ISSUE TITLE
Cinderscapes requires Fabric API >= 0.57.0 but depends on >= 0.47.0

### ISSUE THREAD

**Issue by vlad1m** [TerraformersMC/Cinderscapes#145] opened 2022-10-14 13:15 UTC
I play minecraft with a custom modpack , with around 130 mods,and whenever i try creating a world with cinderscapes mod installed , the game says that ,, errors in the currently selected datapacks prevented the world from loading,,

**Comment by gniftygnome** [comment] 2022-10-14 16:02
I suspect the issue is your modpack or one of the mods in it is providing an incompatible (old) version of TerraBlender, but I can't do more than speculate unless you can provide logs.  However, you could try adding TerraBlender (for fabric) version [1.19.2-2.0.1.128](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric/files/4013815) to your modpack and see if it fixes the issue.

**Comment by vlad1m** [comment] 2022-10-14 16:12
Hmm, but I play on 1.18.2,and the modpack doesn't have terrablender , i gues i should have said the version i play on first

**Comment by gniftygnome** [comment] 2022-10-14 16:28
Then I really need some logs to know what's going on.  :)

**Comment by vlad1m** [comment] 2022-10-14 16:38
[2022-10-14-6.log.gz](https://github.com/TerraformersMC/Cinderscapes/files/9788354/2022-10-14-6.log
ok,here

**Comment by vlad1m** [comment] 2022-10-14 16:41
[2022-10-14-6.log](https://github.com/TerraformersMC/Cinderscapes/files/9788374/2022-10-14-6.log)
ok,here :)

**Comment by gniftygnome** [comment] 2022-10-14 17:00
From the logs:

- cinderscapes 2.0.1
- fabric 0.56.0+1.18.2

```
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_52$class_53 net.minecraft.class_52$class_53.modifyPools(java.util.function.Consumer)'
	at com.terraformersmc.cinderscapes.init.CinderscapesTrades.lambda$init$1(CinderscapesTrades.java:28) ~[cinderscapes-common-2.0.1-b1ea32bca6018fe3.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$2(LootTableEvents.java:78) ~[fabric-loot-api-v2-1.0.0+e747827960-54780e247163c63a.jar:?]
```

Are you able to try upgrading the Fabric API version to 0.58.0 (or at least 0.57.0)?  `FabricLootTableBuilder.modifyPools` was added in 0.57.0 so I need to update Cinderscapes' FAPI dependency to require at least 0.57.0.

**Comment by vlad1m** [comment] 2022-10-14 17:22
K,i'll try

**Comment by vlad1m** [comment] 2022-10-14 17:36
yep, it worked,thanks a lot :)

**Comment by gniftygnome** [comment] 2022-10-14 17:53
Great, I'll bump the FAPI dependency in the next release so it's easier to see what's going on.

**Comment by gniftygnome** [comment] 2022-10-18 18:34
Resolved in today's release.

**Closed as completed by gniftygnome** 2022-10-18 18:34 UTC
Labels: bug
